# Generated by Django 5.0.1 on 2024-01-31 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Atelier",
            fields=[
                (
                    "idAtelier",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("nomAtelier", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="COMMANDE",
            fields=[
                (
                    "idCommande",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("dateCommandee", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="FOURNISSEUR",
            fields=[
                (
                    "idFournisseur",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("nomFournisseur", models.CharField(max_length=255)),
                ("emailFournisseur", models.EmailField(max_length=254)),
                ("telFournisseur", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TYPEPOSITIONNEUR",
            fields=[
                (
                    "idFonctionnementPostionneur",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("descriptionTypePositionneur", models.CharField(max_length=255)),
                ("typePositionneur", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CORPS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idCorps", models.IntegerField(unique=True)),
                ("typeCorps", models.CharField(max_length=255)),
                ("numSerieCorps", models.CharField(max_length=255)),
                ("dnCorps", models.IntegerField()),
                ("pnCorps", models.IntegerField()),
                ("cvCorps", models.IntegerField()),
                ("normeBrideCorps", models.CharField(max_length=255)),
                ("codeCorps", models.CharField(max_length=255)),
                ("matiereArbreCorps", models.CharField(max_length=255)),
                ("matiereSiegeCorps", models.CharField(max_length=255)),
                ("matiereOrgReglantCorps", models.CharField(max_length=255)),
                ("corpsCorps", models.CharField(max_length=255)),
                ("matiereGarnituresCorps", models.CharField(max_length=255)),
                ("typeGarnitureCorps", models.CharField(max_length=255)),
                (
                    "idFournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appliVanne.fournisseur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ACTIONNEUR",
            fields=[
                (
                    "idActionneur",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("numSeriActionneur", models.CharField(max_length=255)),
                ("typeActionneur", models.CharField(max_length=255)),
                ("tailleActionneur", models.IntegerField()),
                ("typeContactActionneur", models.CharField(max_length=255)),
                ("contactOuvertureActionneur", models.BooleanField()),
                ("contactFermetureActionneur", models.BooleanField()),
                ("commandeManuel", models.BooleanField()),
                ("pressionAlimentation", models.IntegerField()),
                ("actionneurDoubleEffet", models.BooleanField()),
                (
                    "idFournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appliVanne.fournisseur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="POSITIONNEUR",
            fields=[
                (
                    "idPositionneur",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("numSeriePositionneur", models.CharField(max_length=255)),
                ("signalEntrePositionneur", models.IntegerField()),
                ("alimentationPositionneur", models.CharField(max_length=255)),
                ("signalSortie", models.IntegerField()),
                ("repereCame", models.IntegerField()),
                ("faceCame", models.IntegerField()),
                ("sensAction", models.IntegerField()),
                ("femerA", models.IntegerField()),
                ("ouvertA", models.IntegerField()),
                (
                    "idFournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appliVanne.fournisseur",
                    ),
                ),
                (
                    "fonctionnementPositionneur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appliVanne.typepositionneur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vanne",
            fields=[
                (
                    "idVanne",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("repereVanne", models.CharField(max_length=255)),
                ("affectationVanne", models.CharField(max_length=255)),
                ("machineVanne", models.CharField(max_length=255)),
                (
                    "idActionneur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appliVanne.actionneur",
                    ),
                ),
                (
                    "idAtelier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appliVanne.atelier",
                    ),
                ),
                (
                    "idCorps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appliVanne.corps",
                        to_field="idCorps",
                    ),
                ),
                (
                    "idPositionneur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appliVanne.positionneur",
                    ),
                ),
                (
                    "numeroCommande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appliVanne.commande",
                    ),
                ),
            ],
        ),
    ]
