# Generated by Django 5.0.1 on 2024-02-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="dateCommandee",
            field=models.CharField(max_length=3),
        ),
    ]
