# Generated by Django 5.0.1 on 2024-02-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0002_alter_commande_datecommandee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="idCommande",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
