# Generated by Django 5.0.1 on 2024-02-05 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0004_vanne_idfournisseurvannes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vanne",
            name="idActionneur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appliVanne.actionneur",
            ),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="idCorps",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appliVanne.corps",
                to_field="idCorps",
            ),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="idFournisseurVannes",
            field=models.ForeignKey(
                default=0,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appliVanne.fournisseur",
            ),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="idPositionneur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appliVanne.positionneur",
            ),
        ),
    ]
