# Generated by Django 5.0.1 on 2024-02-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0005_alter_vanne_idactionneur_alter_vanne_idcorps_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vanne",
            name="machineVanne",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
