# Generated by Django 5.0.1 on 2024-02-05 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0006_alter_vanne_machinevanne"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vanne",
            name="idAtelier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appliVanne.atelier",
            ),
        ),
    ]
