# Generated by Django 5.0.1 on 2024-02-05 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0007_alter_vanne_idatelier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vanne",
            name="affectationVanne",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="numeroCommande",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appliVanne.commande",
            ),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="repereVanne",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
