# Generated by Django 5.0.1 on 2024-02-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0008_alter_vanne_affectationvanne_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vanne",
            name="dateAchat",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vanne",
            name="derniereRevision",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="vanne",
            name="freqRevision",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="vanne",
            name="organeReglant",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vanne",
            name="typeVannes",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vanne",
            name="voirEn",
            field=models.IntegerField(null=True),
        ),
    ]
