# Generated by Django 5.0.1 on 2024-02-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0009_vanne_dateachat_vanne_derniererevision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionneur",
            name="actionneurDoubleEffet",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="commandeManuel",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="contactFermetureActionneur",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="contactOuvertureActionneur",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="numSeriActionneur",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="pressionAlimentation",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="tailleActionneur",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="typeActionneur",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="typeContactActionneur",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
