# Generated by Django 5.0.1 on 2024-02-09 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0010_alter_actionneur_actionneurdoubleeffet_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actionneur",
            old_name="actionneurDoubleEffet",
            new_name="actionneurSimplDoubleEffet",
        ),
        migrations.RenameField(
            model_name="actionneur",
            old_name="contactFermetureActionneur",
            new_name="contactOuvFermActionneur",
        ),
        migrations.RenameField(
            model_name="actionneur",
            old_name="contactOuvertureActionneur",
            new_name="sensActionneur",
        ),
    ]
