# Generated by Django 5.0.1 on 2024-02-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0012_remove_corps_id_alter_corps_idcorps_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="positionneur",
            name="alimentationPositionneur",
        ),
        migrations.AddField(
            model_name="positionneur",
            name="loiPositionneur",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="positionneur",
            name="presionPositionneur",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="positionneur",
            name="typePositionneur",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="faceCame",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="femerA",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="numSeriePositionneur",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="ouvertA",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="repereCame",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="sensAction",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="signalEntrePositionneur",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="signalSortie",
            field=models.IntegerField(null=True),
        ),
    ]
