# Generated by Django 5.0.1 on 2024-02-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0013_remove_positionneur_alimentationpositionneur_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vanne",
            name="numeroCommande",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
