# Generated by Django 5.0.1 on 2024-02-13 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "appliVanne",
            "0017_rename_actionneursimpldoubleeffet_actionneur_actionneur_simpl_double_effet_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atelier",
            name="nom_atelier",
        ),
    ]
