# Generated by Django 5.0.1 on 2024-02-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0018_remove_atelier_nom_atelier"),
    ]

    operations = [
        migrations.AddField(
            model_name="atelier",
            name="nom_atelier",
            field=models.CharField(default="a remplir", max_length=45),
        ),
    ]
