# Generated by Django 5.0.1 on 2024-02-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0019_atelier_nom_atelier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vanne",
            name="en_service_vanne",
            field=models.IntegerField(default=1),
        ),
    ]
