# Generated by Django 5.0.1 on 2024-02-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0021_alter_atelier_nom_atelier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionneur",
            name="id_actionneur",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="atelier",
            name="id_atelier",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="id_corps",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="id_fournisseur",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="id_positionneur",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="typepositionneur",
            name="id_fonctionnement_postionneur",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="id_vanne",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
