# Generated by Django 5.0.1 on 2024-02-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0023_rename_femer_a_positionneur_fermer_a"),
    ]

    operations = [
        migrations.AlterField(
            model_name="positionneur",
            name="sens_action",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
