# Generated by Django 5.0.1 on 2024-02-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0024_alter_positionneur_sens_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vanne",
            name="voir_en",
            field=models.DateField(null=True),
        ),
    ]
