# Generated by Django 5.0.1 on 2024-02-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0025_alter_vanne_voir_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corps",
            name="code_corps",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="corps_corps",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="cv_corps",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="dn_corps",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="matiere_arbre_corps",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="matiere_garnitures_corps",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="matiere_org_reglant_corps",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="matiere_siege_corps",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="norme_bride_corps",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="num_serie_corps",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="pn_corps",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="type_corps",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="type_garniture_corps",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
