# Generated by Django 5.0.1 on 2024-02-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0026_alter_corps_code_corps_alter_corps_corps_corps_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corps",
            name="code_corps",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="corps_corps",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="cv_corps",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="dn_corps",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="matiere_arbre_corps",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="matiere_garnitures_corps",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="matiere_org_reglant_corps",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="matiere_siege_corps",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="norme_bride_corps",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="num_serie_corps",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="pn_corps",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="type_corps",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="corps",
            name="type_garniture_corps",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="face_came",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="fermer_a",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="loi_positionneur",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="num_serie_positionneur",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="ouvert_a",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="presion_positionneur",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="repere_came",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="sens_action",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="signal_entre_positionneur",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="signal_sortie",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="type_positionneur",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="typepositionneur",
            name="description_type_positionneur",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="typepositionneur",
            name="type_positionneur",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="affectation_vanne",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="date_achat",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="derniere_revision",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="en_service_vanne",
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="freq_revision",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="machine_vanne",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="numero_commande",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="organe_reglant",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="repere_vanne",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="type_vannes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="voir_en",
            field=models.DateField(blank=True, null=True),
        ),
    ]
