# Generated by Django 5.0.1 on 2024-02-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0027_alter_corps_code_corps_alter_corps_corps_corps_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vanne",
            name="voir_en",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
