# Generated by Django 5.0.1 on 2024-02-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0028_alter_vanne_voir_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionneur",
            name="actionneur_simpl_double_effet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="commande_manuel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="contact_ouv_ferm_actionneur",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="num_serie_actionneur",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="pression_alimentation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="sens_actionneur",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="taille_actionneur",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="type_actionneur",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="type_contact_actionneur",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
