# Generated by Django 5.0.1 on 2024-03-05 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0029_alter_actionneur_actionneur_simpl_double_effet_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="COMMANDE",
        ),
    ]
