# Generated by Django 5.0.1 on 2024-03-05 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0030_delete_commande"),
    ]

    operations = [
        migrations.CreateModel(
            name="REVISON",
            fields=[
                (
                    "id_revison",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("date_revision", models.DateField(default="2022-01-01")),
                (
                    "commentaire_revision",
                    models.CharField(
                        blank=True,
                        default="Aucun commentaire",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "nom_technicien",
                    models.CharField(
                        blank=True,
                        default="Aucun technicien",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "id_vanne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appliVanne.vanne",
                    ),
                ),
            ],
            options={
                "db_table": "REVISION",
            },
        ),
    ]
