# Generated by Django 5.0.1 on 2024-03-06 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0033_revison_id_revison_vanne"),
    ]

    operations = [
        migrations.RenameField(
            model_name="revison",
            old_name="id_revison_vanne",
            new_name="id_revision_vanne",
        ),
    ]
