# Generated by Django 5.0.1 on 2024-03-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0035_rename_id_revison_revison_id_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="revison",
            name="type_revision",
            field=models.CharField(
                blank=True, default="Aucun type", max_length=255, null=True
            ),
        ),
    ]
