# Generated by Django 5.0.1 on 2024-03-06 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0036_revison_type_revision"),
    ]

    operations = [
        migrations.RenameField(
            model_name="revison",
            old_name="id_vanne",
            new_name="rev_id_vanne",
        ),
    ]
