# Generated by Django 5.0.1 on 2024-03-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0037_rename_id_vanne_revison_rev_id_vanne"),
    ]

    operations = [
        migrations.AddField(
            model_name="vanne",
            name="date_commande",
            field=models.DateField(blank=True, default="0001-01-01", null=True),
        ),
    ]
