# Generated by Django 5.0.1 on 2024-03-07 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0038_vanne_date_commande"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vanne",
            name="date_commande",
            field=models.DateField(
                blank=True, default=datetime.date(2001, 1, 1), null=True
            ),
        ),
    ]
