# Generated by Django 5.0.1 on 2024-03-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0040_vanne_date_commande_bis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vanne",
            name="date_commande_bis",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
