# Generated by Django 5.0.1 on 2024-03-07 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0041_alter_vanne_date_commande_bis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vanne",
            name="date_achat",
        ),
        migrations.RemoveField(
            model_name="vanne",
            name="date_commande_bis",
        ),
    ]
