# Generated by Django 5.0.1 on 2024-03-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0042_remove_vanne_date_achat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revison",
            name="rev_id_vanne",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
