# Generated by Django 5.0.1 on 2024-03-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0043_alter_revison_rev_id_vanne"),
    ]

    operations = [
        migrations.AddField(
            model_name="revison",
            name="ajout_revision",
            field=models.CharField(
                blank=True, default="AUTO", max_length=255, null=True
            ),
        ),
    ]
