# Generated by Django 5.0.1 on 2024-03-12 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0044_revison_ajout_revision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vanne",
            name="id_positionneur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appliVanne.positionneur",
            ),
        ),
    ]
