# Generated by Django 5.0.1 on 2024-03-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0047_alter_vanne_date_commande_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revison",
            name="date_revision",
            field=models.DateField(
                blank=True,
                default="2024-03-18 08:20",
                null=True,
                verbose_name="Date de la révision",
            ),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="date_commande",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de la commande"
            ),
        ),
    ]
