# Generated by Django 5.0.1 on 2024-03-18 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0048_alter_revison_date_revision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revison",
            name="date_revision",
            field=models.DateField(
                blank=True,
                default=datetime.datetime.now,
                null=True,
                verbose_name="Date de la révision",
            ),
        ),
    ]
