# Generated by Django 5.0.1 on 2024-03-18 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0053_alter_revison_date_revision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionneur",
            name="actionneur_simpl_double_effet",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Actionneur simple/double effet",
            ),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="commande_manuel",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Commande manuelle de l'actionneur",
            ),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="contact_ouv_ferm_actionneur",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Contact ouverture/fermeture de l'actionneur",
            ),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="id_actionneur",
            field=models.AutoField(
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID de l'actionneur",
            ),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="id_fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appliVanne.fournisseur",
                verbose_name="ID du fournisseur",
            ),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="num_serie_actionneur",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Numéro de série de l'actionneur",
            ),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="pression_alimentation",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Pression d'alimentation de l'actionneur",
            ),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="sens_actionneur",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Sens de l'actionneur",
            ),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="taille_actionneur",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Taille de l'actionneur",
            ),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="type_actionneur",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Type de l'actionneur",
            ),
        ),
        migrations.AlterField(
            model_name="actionneur",
            name="type_contact_actionneur",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Type de contact de l'actionneur",
            ),
        ),
        migrations.AlterField(
            model_name="atelier",
            name="id_atelier",
            field=models.AutoField(
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID de l'atelier",
            ),
        ),
        migrations.AlterField(
            model_name="atelier",
            name="nom_atelier",
            field=models.CharField(
                default="a remplir",
                max_length=45,
                unique=True,
                verbose_name="Nom de l'atelier",
            ),
        ),
        migrations.AlterField(
            model_name="corps",
            name="code_corps",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Code du corps"
            ),
        ),
        migrations.AlterField(
            model_name="corps",
            name="corps_corps",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Corps du corps"
            ),
        ),
        migrations.AlterField(
            model_name="corps",
            name="cv_corps",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="CV du corps"
            ),
        ),
        migrations.AlterField(
            model_name="corps",
            name="dn_corps",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="DN du corps"
            ),
        ),
        migrations.AlterField(
            model_name="corps",
            name="id_corps",
            field=models.AutoField(
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID du corps",
            ),
        ),
        migrations.AlterField(
            model_name="corps",
            name="id_fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appliVanne.fournisseur",
                verbose_name="ID du fournisseur",
            ),
        ),
        migrations.AlterField(
            model_name="corps",
            name="matiere_arbre_corps",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Matière de l'arbre du corps",
            ),
        ),
        migrations.AlterField(
            model_name="corps",
            name="matiere_garnitures_corps",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Matière des garnitures du corps",
            ),
        ),
        migrations.AlterField(
            model_name="corps",
            name="matiere_org_reglant_corps",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Matière de l'organe réglant du corps",
            ),
        ),
        migrations.AlterField(
            model_name="corps",
            name="matiere_siege_corps",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Matière du siège du corps",
            ),
        ),
        migrations.AlterField(
            model_name="corps",
            name="norme_bride_corps",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Norme de bride du corps",
            ),
        ),
        migrations.AlterField(
            model_name="corps",
            name="num_serie_corps",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Numéro de série du corps",
            ),
        ),
        migrations.AlterField(
            model_name="corps",
            name="pn_corps",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="PN du corps"
            ),
        ),
        migrations.AlterField(
            model_name="corps",
            name="type_corps",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Type de corps"
            ),
        ),
        migrations.AlterField(
            model_name="corps",
            name="type_garniture_corps",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Type de garniture du corps",
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="email_fournisseur",
            field=models.EmailField(
                max_length=254, verbose_name="Adresse e-mail du fournisseur"
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="id_fournisseur",
            field=models.AutoField(
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID du fournisseur",
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="nom_fournisseur",
            field=models.CharField(max_length=255, verbose_name="Nom du fournisseur"),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="tel_fournisseur",
            field=models.CharField(
                max_length=255, verbose_name="Numéro de téléphone du fournisseur"
            ),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="face_came",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Face de la came du positionneur"
            ),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="fermer_a",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Fermer à du positionneur"
            ),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="fonctionnement_positionneur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appliVanne.typepositionneur",
                verbose_name="Fonctionnement du positionneur",
            ),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="id_fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appliVanne.fournisseur",
                verbose_name="ID du fournisseur",
            ),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="id_positionneur",
            field=models.AutoField(
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID du positionneur",
            ),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="loi_positionneur",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Loi du positionneur",
            ),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="num_serie_positionneur",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Numéro de série du positionneur",
            ),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="ouvert_a",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Ouvert à du positionneur"
            ),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="presion_positionneur",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Pression du positionneur",
            ),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="repere_came",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Repère de la came du positionneur"
            ),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="sens_action",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Sens d'action du positionneur",
            ),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="signal_entre_positionneur",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Signal d'entrée du positionneur"
            ),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="signal_sortie",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Signal de sortie du positionneur"
            ),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="type_positionneur",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Type de positionneur",
            ),
        ),
        migrations.AlterField(
            model_name="revison",
            name="ajout_revision",
            field=models.CharField(
                blank=True,
                default="AUTO",
                max_length=255,
                null=True,
                verbose_name="Ajout de révision",
            ),
        ),
        migrations.AlterField(
            model_name="revison",
            name="commentaire_revision",
            field=models.CharField(
                blank=True,
                default="Aucun commentaire",
                max_length=255,
                null=True,
                verbose_name="Commentaire de révision",
            ),
        ),
        migrations.AlterField(
            model_name="revison",
            name="detail_commentaire",
            field=models.CharField(
                blank=True,
                default="Aucun détail",
                max_length=1500000,
                null=True,
                verbose_name="Détail de révision",
            ),
        ),
        migrations.AlterField(
            model_name="revison",
            name="id_revision",
            field=models.AutoField(
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID de la révision",
            ),
        ),
        migrations.AlterField(
            model_name="revison",
            name="id_revision_vanne",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="ID de la révision de la vanne",
            ),
        ),
        migrations.AlterField(
            model_name="revison",
            name="nom_technicien",
            field=models.CharField(
                blank=True,
                default="Aucun technicien",
                max_length=255,
                null=True,
                verbose_name="Nom du technicien",
            ),
        ),
        migrations.AlterField(
            model_name="revison",
            name="rev_id_vanne",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="ID de la vanne"
            ),
        ),
        migrations.AlterField(
            model_name="revison",
            name="type_revision",
            field=models.CharField(
                blank=True,
                default="Aucun type",
                max_length=255,
                null=True,
                verbose_name="Type de révision",
            ),
        ),
        migrations.AlterField(
            model_name="typepositionneur",
            name="description_type_positionneur",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Description du type de positionneur",
            ),
        ),
        migrations.AlterField(
            model_name="typepositionneur",
            name="id_fonctionnement_postionneur",
            field=models.AutoField(
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID du type de positionneur",
            ),
        ),
        migrations.AlterField(
            model_name="typepositionneur",
            name="type_positionneur",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Type de positionneur"
            ),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="affectation_vanne",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Affectation de la vanne",
            ),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="en_service_vanne",
            field=models.IntegerField(blank=True, default=1, verbose_name="En service"),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="freq_revision",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Fréquence de révision"
            ),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="id_actionneur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appliVanne.actionneur",
                verbose_name="ID de l'actionneur",
            ),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="id_atelier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appliVanne.atelier",
                verbose_name="ID de l'atelier",
            ),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="id_corps",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appliVanne.corps",
                verbose_name="ID du corps",
            ),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="id_fournisseur_vannes",
            field=models.ForeignKey(
                default=0,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appliVanne.fournisseur",
                verbose_name="ID du fournisseur de vannes",
            ),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="id_positionneur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appliVanne.positionneur",
                verbose_name="ID du positionneur",
            ),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="id_vanne",
            field=models.AutoField(
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID de la vanne",
            ),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="machine_vanne",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Machine de la vanne",
            ),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="numero_commande",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Numéro de commande"
            ),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="organe_reglant",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Organe réglant"
            ),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="repere_vanne",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Repère de la vanne"
            ),
        ),
        migrations.AlterField(
            model_name="vanne",
            name="type_vannes",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Type de vannes"
            ),
        ),
    ]
