# Generated by Django 5.0.1 on 2024-03-19 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0056_typerevision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revison",
            name="type_revision",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appliVanne.typerevision",
                verbose_name="ID du  type de revision",
            ),
        ),
    ]
