# Generated by Django 5.0.1 on 2024-03-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0057_alter_revison_type_revision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="positionneur",
            name="fermer_a",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Fermer à du positionneur",
            ),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="ouvert_a",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Ouvert à du positionneur",
            ),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="repere_came",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Repère de la came du positionneur",
            ),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="signal_entre_positionneur",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Signal d'entrée du positionneur",
            ),
        ),
        migrations.AlterField(
            model_name="positionneur",
            name="signal_sortie",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Signal de sortie du positionneur",
            ),
        ),
    ]
