# Generated by Django 5.0.1 on 2024-03-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0059_alter_revison_nom_technicien"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revison",
            name="nom_technicien",
            field=models.CharField(
                blank=True,
                default="Aucun détail",
                max_length=1500000,
                null=True,
                verbose_name="Détail de révision",
            ),
        ),
    ]
