# Generated by Django 5.0.1 on 2024-03-21 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appliVanne", "0061_alter_revison_nom_technicien"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="revison",
            name="nom_technicien",
        ),
    ]
